import type { TourStep } from "./tour";

/**
 * Task "lessons" — short, replayable narrated walkthroughs for specific jobs
 * (add a project, install an agent, use a local model, …). Each lesson is a
 * step list run through the same engine as the high-level tour (`TourHost` /
 * `useTourStore.startLesson`), so it reuses the spotlight, click-blocking, and
 * Back/Next navigation. Picked from the `LessonsMenu`.
 *
 * Most steps spotlight a persistent entry-point control (the + button, the gear,
 * the 🧠 menu) by a verified selector; menu/dialog internals — which only exist
 * while open and which the narrated, click-blocking overlay can't keep pinned —
 * are described as centered cards (`anchor: null`). Copy matches the terse,
 * friendly onboarding voice.
 *
 * Order is meaningful: lessons run easiest → hardest and are grouped into tiers
 * (`LESSON_CATEGORIES`). `LESSONS` stays sorted so each category's lessons are
 * contiguous and the picker can render a header per tier just by walking the
 * array. Within a tier the lessons themselves also ramp from simplest to most
 * involved.
 */

/** Difficulty tiers, in the order the picker shows them (easy → hard). */
export const LESSON_CATEGORIES = ["Basics", "Agents & models", "Advanced"] as const;
export type LessonCategory = (typeof LESSON_CATEGORIES)[number];

export interface Lesson {
  /** Stable id (also the React key in the picker). */
  id: string;
  /** Difficulty tier; groups the lesson under a header in the picker. */
  category: LessonCategory;
  /** Menu label. */
  title: string;
  /** One-line description shown under the title in the picker. */
  blurb: string;
  steps: TourStep[];
}

/** Reveal the right-side file panel so a step's anchor exists to spotlight.
 *  AppShell listens for this (the panel is otherwise hover-revealed). */
const revealFilePanel = () => window.dispatchEvent(new Event("eldrun:reveal-right-panel"));

export const LESSONS: Lesson[] = [
  // ── Basics ──────────────────────────────────────────────────────────────
  {
    id: "add-project",
    category: "Basics",
    title: "Add a new project",
    blurb: "Create or import a project — each gets its own terminal, tabs, and file tree.",
    steps: [
      {
        id: "pill-strip",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Your projects live here",
        body: "Every active project shows up as a pill in this strip. Click one to switch to it — each project keeps its own terminal, tabs, and file tree.",
      },
      {
        id: "add-button",
        anchor: '[data-hint-anchor="add-project"]',
        placement: "bottom",
        title: "The + button",
        body: "Click + to open the add menu. It's your single entry point for starting a brand-new project, importing an existing folder, or grouping projects into a box.",
      },
      {
        id: "add-menu",
        anchor: null,
        placement: "bottom",
        title: "New, Import, or Box",
        body: "The menu offers New Project (scaffold a fresh project), Import Project (register a folder you already have), and New Box (a meta-group for related pills). Pick New Project.",
      },
      {
        id: "new-dialog",
        anchor: null,
        placement: "bottom",
        title: "Fill in the details",
        body: "The New Project dialog asks for a name and an optional description, and lets you pick a Git hosting option (no git, a local-only repo, or push to GitHub/GitLab as private or public). Flip the \"Remote (SSH) project\" toggle to host it on another machine instead.",
      },
      {
        id: "scaffold-create",
        anchor: null,
        placement: "bottom",
        title: "What you get",
        body: "Hit Create and Eldrun makes the project folder under your projects directory (~/eldrun/projects by default — the Location picker changes it), scaffolds AGENTS.md, CLAUDE.md, .gitignore, README and friends, and initializes the repo. Tick \"Skip scaffolding\" if you'd rather start empty.",
      },
      {
        id: "publish-remote",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Advanced: connect a remote",
        body: "To put it on GitHub or GitLab, pick a \"Push to GitHub/GitLab\" hosting option in the dialog — or later, right-click the project's pill → \"Publish to GitHub / GitLab…\", choose the provider and public/private. Eldrun runs that provider's CLI (gh or glab) to create the repo and push. Needs the chosen CLI installed and signed in, or a token under ⚙ Settings → Git Hosting.",
      },
    ],
  },
  {
    id: "import-project",
    category: "Basics",
    title: "Import a project",
    blurb: "Register an existing folder — or a remote SSH host — without touching its contents.",
    steps: [
      {
        id: "open-add-menu",
        anchor: '[data-hint-anchor="add-project"]',
        placement: "top",
        title: "Open the add menu",
        body: "Click the + button beside your project pills. It opens a small menu with New Project, Import Project, and New Box.",
      },
      {
        id: "pick-import",
        anchor: null,
        placement: "bottom",
        title: "Choose \"Import Project\"",
        body: "Pick Import Project from that menu. A centered dialog opens for registering a folder you already have.",
      },
      {
        id: "browse-folder",
        anchor: null,
        placement: "bottom",
        title: "Point at your folder",
        body: "Under Source folder, hit Browse… and select the existing project directory. Eldrun reads it in place and does not modify its contents.",
      },
      {
        id: "import-mode",
        anchor: null,
        placement: "bottom",
        title: "Keep, copy, or move",
        body: "Import mode lets you keep the folder where it is, or copy/move it into Eldrun's projects folder. Set a name and a Git hosting option, then confirm to add the pill.",
      },
      {
        id: "remote-import",
        anchor: null,
        placement: "bottom",
        title: "Remote? Flip the SSH toggle",
        body: "Tick \"Remote (SSH) project\" to import a folder living on another host. Eldrun pairs it with a synced local working copy: agent tabs work in the local copy by default, while shells, file browsing, and git reach the host over SSH/SFTP (with an optional OpenVPN step). No local mount needed.",
      },
      {
        id: "publish-remote",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Advanced: connect a remote",
        body: "Imported a folder that isn't on a remote yet? Right-click its pill → \"Publish to GitHub / GitLab…\", choose the provider and public/private, and Eldrun runs that provider's CLI (gh or glab) to create the repo and push your code. Needs the chosen CLI installed and authenticated, or a token under ⚙ Settings → Git Hosting.",
      },
    ],
  },
  {
    id: "add-tab",
    category: "Basics",
    title: "Add a tab",
    blurb: "Open a new agent, shell, or file-browser tab in any subwindow.",
    steps: [
      {
        id: "find-plus",
        anchor: '[data-hint-anchor="tab-add"]',
        placement: "bottom",
        title: "The + button",
        body: "Every tab bar ends with a + button. Click it to open the new-tab menu for that subwindow.",
      },
      {
        id: "the-menu",
        anchor: null,
        placement: "bottom",
        title: "Pick what to open",
        body: "The menu groups your choices: an Agents section (Claude, Codex, Gemini and any other installed CLIs), a Local Model section (your set on-device model), Shell and Files, a Monitoring section (Disk Usage, Network Traffic), and Calendar.",
      },
      {
        id: "shell-files",
        anchor: null,
        placement: "bottom",
        title: "Shell, Files & more",
        body: "Choose Shell for a plain terminal in the project folder, or Files for an in-app file browser. The same menu also opens a Disk Usage or Network Traffic monitor and a Calendar. The new tab opens focused in this subwindow.",
      },
      {
        id: "rename-close",
        anchor: null,
        placement: "bottom",
        title: "Rename, close, reopen",
        body: "Right-click a tab for its menu — Rename, Close, Close others, or close everything to one side. Shift+right-click renames inline straight away; the × on a tab closes it. Reopening a closed agent respawns it fresh from the same + menu.",
      },
    ],
  },
  {
    id: "native-viewer",
    category: "Basics",
    title: "Open a file in the viewer",
    blurb: "Reveal the file tree and open files in Eldrun's built-in viewers — no external app.",
    steps: [
      {
        id: "reveal-tree",
        anchor: '[data-hint-anchor="file-tree-edge"]',
        placement: "left",
        title: "Reveal the file tree",
        body: "Push your cursor to the right edge of the window to slide out the project file tree.",
        prepare: revealFilePanel,
      },
      {
        id: "pin-panel",
        anchor: ".right-panel-pin",
        placement: "left",
        title: "Pin it open",
        body: "The panel auto-hides when your cursor leaves. Click the 📌 to keep it docked while you browse.",
        prepare: revealFilePanel,
      },
      {
        id: "open-file",
        anchor: null,
        placement: "bottom",
        title: "Double-click a file",
        body: "Double-click any file to open it; single-click a folder to step into it. You can also drag a file onto a tab bar to open it there.",
      },
      {
        id: "viewer-pane",
        anchor: null,
        placement: "bottom",
        title: "It opens in-app",
        body: "PDFs, images (and GIFs), markdown, code, notebooks, YAML/JSON, tables and spreadsheets, diffs, audio/video, and TeX render in Eldrun's native viewer — no external app. The built-in viewer wins whenever one applies.",
      },
      {
        id: "default-app",
        anchor: null,
        placement: "bottom",
        title: "Change the handler",
        body: "Right-click a file → \"Set default app…\" to send a type to an external app instead. Toggle native viewers per type under the file panel's own ⚙ (Project settings → Native Viewers).",
      },
    ],
  },
  {
    id: "arrange-tabs",
    category: "Basics",
    title: "Arrange tabs",
    blurb: "Reorder tabs, split panes, drag files in from the tree, and pop tabs into their own window.",
    steps: [
      {
        id: "intro",
        anchor: null,
        placement: "bottom",
        title: "Make room your way",
        body: "Drag to arrange everything: reorder tabs, split the view, pull files in from the file tree, and pop panes out into their own windows. Let's walk through it.",
      },
      {
        id: "tab-bar",
        anchor: ".tab-bar",
        placement: "bottom",
        title: "The tab bar",
        body: "Each subwindow has its own tab strip. Drag a tab left or right within this bar to reorder it.",
      },
      {
        id: "split",
        anchor: null,
        placement: "bottom",
        title: "Split a pane",
        body: "Drag a tab onto the edge of a pane — top, bottom, left, or right — to split the view and tile it side-by-side or stacked. Drop it in the middle instead to move it into that group.",
      },
      {
        id: "drag-from-tree",
        anchor: '[data-hint-anchor="file-tree-edge"]',
        placement: "left",
        title: "Drag a file in from the tree",
        body: "Slide out the file tree on the right and drag an openable file straight into the layout — drop it on a tab bar to add it there, on a pane edge to split, or in a pane's center to merge. It opens right where you drop it.",
        prepare: revealFilePanel,
      },
      {
        id: "detach",
        anchor: null,
        placement: "bottom",
        title: "Pop out a window",
        body: "Drag a tab (or a whole tab bar) out of the app to detach it into its own floating OS window. Drag it back over Eldrun to dock it again.",
      },
      {
        id: "drag-to-detached",
        anchor: null,
        placement: "bottom",
        title: "Drop across windows",
        body: "That same drag reaches popped-out windows: drag a tab — or a file from the tree — onto a detached window that's in front and it docks there. Release over empty desktop instead to open it in a brand-new window.",
      },
      {
        id: "outro",
        anchor: null,
        placement: "bottom",
        title: "That's it",
        body: "Reorder within a bar, drop on an edge to split or a center to merge, pull files in from the tree, and drag tabs out to detach or onto another window. Rearrange freely — your layout is saved.",
      },
    ],
  },
  {
    id: "yaml-viewer",
    category: "Basics",
    title: "Edit YAML & JSON visually",
    blurb: "Open a config file as editable cards or a tree — comments and formatting survive every edit.",
    steps: [
      {
        id: "open-yaml",
        anchor: null,
        placement: "bottom",
        title: "Open a .yaml, .yml, or .json file",
        body: "Double-click any YAML or JSON file in the tree. Instead of raw text, it opens in a structured viewer that understands the file's shape — while still being the exact same file underneath.",
      },
      {
        id: "three-views",
        anchor: null,
        placement: "bottom",
        title: "Cards, Tree, or Source",
        body: "The toolbar offers three views of the same file. Cards (the default) shows one level of the structure at a time as navigable cards; Tree shows the whole thing as nested, indented rows; Source is the raw text. Switch freely — they're three windows onto one document.",
      },
      {
        id: "drill-cards",
        anchor: null,
        placement: "bottom",
        title: "Drill through Cards",
        body: "In Cards, each card shows its own scalar fields; click a card's title (or its \"N groups\" footer) to open it and reveal its nested collections as the next level down. A breadcrumb tracks where you are, and the current level's siblings let you step sideways without going up first.",
      },
      {
        id: "edit-safely",
        anchor: null,
        placement: "bottom",
        title: "Edits keep your comments",
        body: "Change a value, add or delete a field, or drag a card's grip to reorder among its siblings — every action splices just that span of text, so your # comments, quoting style, and untouched lines stay byte-for-byte. It's an ordinary dirty/undo/save edit, and a comment travels with the key it describes.",
      },
      {
        id: "copy-paste",
        anchor: null,
        placement: "bottom",
        title: "Copy entries around",
        body: "Each entry has a copy button feeding an app-wide buffer; a click-placed paste cursor drops it back in — but only where it fits (a mapping entry into a map, an item into a list), so a paste can never tear the file. Anything the viewer can't safely rewrite is shown read-only, never mangled.",
      },
    ],
  },
  {
    id: "pdf-viewer",
    category: "Basics",
    title: "Read and reshape PDFs",
    blurb: "Jump by chapter, then reorder, rotate, delete, and merge pages — nothing is written until you save.",
    steps: [
      {
        id: "open-pdf",
        anchor: null,
        placement: "bottom",
        title: "Open a PDF in-app",
        body: "Double-click a PDF and it renders in Eldrun's own viewer — no external app — with a zoom, find, and print toolbar along the top and a thumbnail page rail down the side.",
      },
      {
        id: "contents",
        anchor: null,
        placement: "bottom",
        title: "The Contents sidebar",
        body: "Click the ☰ at the far left of the toolbar to open Contents: the document's chapters and bookmarks. If a PDF has no embedded outline, Eldrun infers a heading tree from the text's typography instead. Click any entry to jump straight there.",
      },
      {
        id: "page-tools",
        anchor: null,
        placement: "bottom",
        title: "Rearrange pages",
        body: "In the page rail you can drag pages to reorder them, shift-select a range, rotate, delete, or duplicate — and even pull pages between two open PDFs. The viewer shows an arrangement, not the file, so these are just moves you're staging.",
      },
      {
        id: "save-pdf",
        anchor: null,
        placement: "bottom",
        title: "Save writes the new file",
        body: "Nothing touches the PDF on disk until you Save — only then is the rearranged document written out. Until then, undo/redo covers every page move, exactly like editing text.",
      },
      {
        id: "synctex",
        anchor: null,
        placement: "bottom",
        title: "TeX authors: SyncTeX",
        body: "For a PDF built from LaTeX, the viewer supports SyncTeX both ways — click in the PDF to jump to the source line, and jump from the source to the page. Find and print work as you'd expect from the toolbar.",
      },
    ],
  },
  {
    id: "run-python",
    category: "Basics",
    title: "Run and debug Python",
    blurb: "Run or debug a .py file straight from the viewer — breakpoints, pdb, and go-to-definition included.",
    steps: [
      {
        id: "open-py",
        anchor: null,
        placement: "bottom",
        title: "Open a Python file",
        body: "Open any .py file in the viewer. A small run bar appears with Run file and Debug file — no launch config to write.",
      },
      {
        id: "run-file",
        anchor: null,
        placement: "bottom",
        title: "Run file",
        body: "Click Run file and Eldrun opens a terminal tab that runs it. Because it's a real tab, it inherits the project's locality for free — a remote SSH host or a Docker container — and stays fully interactive: input(), Ctrl+C, and output that survives after the process exits.",
      },
      {
        id: "breakpoints",
        anchor: null,
        placement: "bottom",
        title: "Set breakpoints in the gutter",
        body: "Click the line-number gutter to drop a breakpoint. It snaps to the next executable line (pdb refuses blank or comment lines), and if you type above it the marker re-points so it always sits on the right statement.",
      },
      {
        id: "debug-file",
        anchor: null,
        placement: "bottom",
        title: "Debug file",
        body: "Debug file launches the same terminal tab under pdb, pre-loaded with your gutter breakpoints and run to the first one. Step, inspect, and continue right there in the tab. (Debugging is behind the experimental flag — on by default in debug mode.)",
      },
      {
        id: "go-to-def",
        anchor: null,
        placement: "bottom",
        title: "Jump to a definition",
        body: "Ctrl+click a name to go to where it's defined — Eldrun walks the import graph (relative imports, aliases, __init__ re-exports, src-layout). Only names it can actually follow are underlined, so the affordance never lies.",
      },
    ],
  },
  {
    id: "file-search",
    category: "Basics",
    title: "Search inside your project",
    blurb: "Find files by name or search their contents from the tree — every hit jumps and opens.",
    steps: [
      {
        id: "reveal-tree",
        anchor: '[data-hint-anchor="file-tree-edge"]',
        placement: "left",
        title: "Open the file tree",
        body: "Push your cursor to the right edge of the window to slide out the file tree. Its search box sits at the top, above the listing.",
        prepare: revealFilePanel,
      },
      {
        id: "name-vs-content",
        anchor: null,
        placement: "bottom",
        title: "Name or Content",
        body: "Type in the box and pick a mode. Name matches a case-insensitive substring of file paths (basename hits rank first — deliberately not a fuzzy match that lights up everything). Content searches the actual lines inside your files, the same engine as the Search view.",
      },
      {
        id: "jump-and-open",
        anchor: null,
        placement: "bottom",
        title: "Every hit jumps and opens",
        body: "Click a result to reveal and select it in the tree; a content hit also opens the file at the matched line. So search doubles as fast navigation, not just a lookup.",
      },
      {
        id: "scope-root",
        anchor: null,
        placement: "bottom",
        title: "This folder, or the whole project",
        body: "By default the search is confined to the folder you're browsing. Flip the Root toggle to search the entire project instead. (It's local-source only — both modes walk the canonical local path.)",
      },
    ],
  },
  {
    id: "calendar",
    category: "Basics",
    title: "Plan with the calendar",
    blurb: "Open a calendar tab — drag to create events, set reminders, and import/export .ics.",
    steps: [
      {
        id: "open-calendar",
        anchor: '[data-hint-anchor="tab-add"]',
        placement: "bottom",
        title: "Open a Calendar tab",
        body: "Click the + on any tab bar and pick Calendar (marked ◆). It opens a full calendar in that subwindow. Your calendars and events are global — one store shared across every project and box.",
      },
      {
        id: "views",
        anchor: null,
        placement: "bottom",
        title: "Day, Week, Month, Agenda, Tasks",
        body: "The toolbar switches views: Day and Week hour grids, a Month (or multi-week) grid with spanning bars, a flat Agenda list of what's upcoming, and Tasks — your to-dos (VTODO). A search box and a mini-month sidebar help you jump around.",
      },
      {
        id: "drag-create",
        anchor: null,
        placement: "bottom",
        title: "Drag to create and adjust",
        body: "In a Day/Week grid, drag across the hours to create an event, then drag its body to move it or its edge to resize. A now-line marks the current time. Everything is direct manipulation — no dialog needed to block out time.",
      },
      {
        id: "event-editor",
        anchor: null,
        placement: "bottom",
        title: "Repeats, reminders, categories",
        body: "Double-click an event for the editor: set a recurrence rule, add reminders (which fire an OS notification and an in-app popup you can snooze), and tag it with a category color. Editing a repeating event asks whether you mean this occurrence or all of them.",
      },
      {
        id: "ics",
        anchor: null,
        placement: "bottom",
        title: "Import & export .ics",
        body: "The toolbar imports and exports iCalendar (.ics) — VEVENT, VTODO, VALARM and RRULE all round-trip — so you can pull in an existing calendar or hand one off to another app.",
      },
    ],
  },
  {
    id: "usage-recap",
    category: "Basics",
    title: "See your usage recap",
    blurb: "A private daily summary: agents used, prompts asked, file churn, commits, and time per project.",
    steps: [
      {
        id: "what-it-is",
        anchor: ".project-pills-region",
        placement: "top",
        title: "A recap of your day",
        body: "Eldrun keeps a rolling, local-only tally of how you worked: which agents and local models you used, how many prompts and shell commands you ran, files created/modified/deleted, tabs opened, plus commits and time per project pulled from their sources.",
      },
      {
        id: "when-it-opens",
        anchor: null,
        placement: "bottom",
        title: "It pops up once a day",
        body: "By default the recap for the day just finished appears on your first launch each day. It's a summary popup — you can read it and dismiss it. Everything it shows was counted locally; nothing leaves your machine.",
      },
      {
        id: "windows",
        anchor: null,
        placement: "bottom",
        title: "Day, week, month",
        body: "Inside the recap you can switch between This day, This week, and This month to zoom out from a single day's activity to longer trends across all your projects.",
      },
      {
        id: "open-anytime",
        anchor: '[data-hint-anchor="settings"]',
        placement: "bottom",
        title: "Open it any time — or turn it off",
        body: "Don't want to wait for tomorrow's launch? Open ⚙ Settings → Usage stats → \"Open usage stats\". The same panel has \"Show the recap at the start of each day\" — turning it off stops the popup, not the counting.",
      },
    ],
  },

  // ── Agents & models ─────────────────────────────────────────────────────
  {
    id: "install-agent",
    category: "Agents & models",
    title: "Choose an AI agent",
    blurb: "Pick an AI coding agent for a tab, and install its CLI so it shows up.",
    steps: [
      {
        id: "open-add-menu",
        anchor: '[data-hint-anchor="tab-add"]',
        placement: "bottom",
        title: "Add an agent tab",
        body: "The + button on any tab bar opens the add menu. That's where you pick which AI agent to launch in a new tab.",
      },
      {
        id: "pick-from-list",
        anchor: null,
        placement: "bottom",
        title: "Pick an agent",
        body: "The menu lists agents like Claude, Codex, Gemini, Mistral, Aider, OpenCode, Cursor, Copilot, Grok, Qwen, and OpenClaw. Click one to spawn a tab running that agent in the project folder.",
      },
      {
        id: "only-installed",
        anchor: null,
        placement: "bottom",
        title: "Only installed agents appear",
        body: "The menu hides any agent whose CLI isn't on your system — Eldrun probes each one's command first. If yours is missing, you just need to install it.",
      },
      {
        id: "manage-agents",
        anchor: '[data-hint-anchor="settings"]',
        placement: "bottom",
        title: "Install a missing agent",
        body: "Open ⚙ → Manage Agents to install an agent CLI with one click (the installer's output streams right there), or run its vendor command in a terminal tab. Most CLIs need npm — the panel offers to install Node.js first if it's missing. The agent then appears in the + menu.",
      },
      {
        id: "set-default",
        anchor: '[data-hint-anchor="settings"]',
        placement: "bottom",
        title: "Agents come back after a relaunch",
        body: "Shell and Files tabs are always restored when Eldrun relaunches. Claude and Codex agent tabs are restored too — they resume their previous conversation. Other agents start fresh from the + menu.",
      },
    ],
  },
  {
    id: "local-model",
    category: "Agents & models",
    title: "Models & agents",
    blurb: "The 🧠 menu hubs your on-device Ollama models and your installed AI agents.",
    steps: [
      {
        id: "brain-button",
        anchor: '[aria-label="Local model"]',
        placement: "bottom",
        title: "The model & agent menu",
        body: "This 🧠 button is your model-and-agent hub: loaded and installed local (Ollama) models up top — those run on-device, nothing leaves your machine — and your installed AI agents below. Hover it to open; if Ollama isn't installed yet it offers \"Install Ollama…\".",
      },
      {
        id: "pick-default",
        anchor: null,
        placement: "bottom",
        title: "Pick a model",
        body: "Models loaded in memory show a green lamp. Click a model's name to make it your default local model; models on disk can be loaded into memory from the same list.",
      },
      {
        id: "role-chips",
        anchor: null,
        placement: "bottom",
        title: "Assign tasks",
        body: "Tag a loaded model with the Autocomplete, Grammar, or Tabs chips to pin it to that job. Several models can each own a different task; load just one and it auto-handles everything.",
      },
      {
        id: "manage-models",
        anchor: '[data-hint-anchor="settings"]',
        placement: "bottom",
        title: "Manage models",
        body: "\"Manage local models…\" (or the gear → Settings → Ollama) is where you pull new models, watch download progress, and delete ones you no longer need.",
      },
      {
        id: "agents-section",
        anchor: null,
        placement: "bottom",
        title: "Agents live here too",
        body: "Below the models, the Agents section lists every AI agent CLI Eldrun detected (a green lamp means it's installed). \"Manage agents…\" installs missing ones — the same agents you then launch from any tab's + menu.",
      },
      {
        id: "use-autocomplete",
        anchor: null,
        placement: "bottom",
        title: "Use it while editing",
        body: "In native file viewers, ghost-text suggestions appear when you pause typing — or press Ctrl+Space to ask directly. Tab accepts the whole suggestion, → takes just the next word, Shift+Tab cycles the completion length (sentence → block → scope). It's opt-in per file type (a privacy gate).",
      },
    ],
  },
  {
    id: "add-local-model",
    category: "Agents & models",
    title: "Add a local model or agent",
    blurb: "Pull an on-device Ollama model, or install an AI agent CLI so it shows up.",
    steps: [
      {
        id: "open-brain",
        anchor: '[aria-label="Local model"]',
        placement: "bottom",
        title: "Open the 🧠 menu",
        body: "This button is your model-and-agent hub. Hover it to open. Local (Ollama) models run on-device — nothing leaves your machine — and your installed agent CLIs are listed below them.",
      },
      {
        id: "manage-models",
        anchor: null,
        placement: "bottom",
        title: "Manage local models…",
        body: "Click \"Manage local models…\" at the bottom of the menu (it reads \"Install Ollama…\" instead if Ollama isn't on your system yet — install that first). It opens the Ollama panel under ⚙ Settings.",
      },
      {
        id: "pull-from-catalog",
        anchor: null,
        placement: "bottom",
        title: "Pull a model",
        body: "Browse the catalog, sort by size or popularity, and hit Pull on one you want. A progress bar tracks the download — you can pause and resume it, and the model loads into the 🧠 menu when it's done.",
      },
      {
        id: "pull-by-name",
        anchor: null,
        placement: "bottom",
        title: "Or pull any model by name",
        body: "Not in the catalog? Type any Ollama registry ref (e.g. qwen2.5-coder:7b) into the free-text pull field and confirm. Eldrun fetches it the same way.",
      },
      {
        id: "manage-agents",
        anchor: '[data-hint-anchor="settings"]',
        placement: "bottom",
        title: "Add an AI agent instead",
        body: "Back in the 🧠 menu, \"Manage agents…\" (or ⚙ → Manage Agents) one-click-installs an agent CLI — Claude, Codex, Gemini and friends — or runs its vendor command in a terminal tab. Installed agents then appear in any tab's + menu.",
      },
    ],
  },

  // ── Advanced ────────────────────────────────────────────────────────────
  {
    id: "project-boxes",
    category: "Advanced",
    title: "Group projects into a box",
    blurb: "Bundle related projects under one box pill — drag them in, switch between them, open the box scope.",
    steps: [
      {
        id: "why-boxes",
        anchor: ".project-pills-region",
        placement: "top",
        title: "When pills pile up",
        body: "Once you have a lot of projects, this strip gets crowded. A box is a single pill that meta-groups related projects together so the strip stays tidy.",
      },
      {
        id: "new-box",
        anchor: '[data-hint-anchor="add-project"]',
        placement: "bottom",
        title: "Create a box",
        body: "Click + beside your pills and pick New Box from the menu. Give it a name — an empty box pill (marked ▣) appears in the strip with a member count of 0.",
      },
      {
        id: "assign-members",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Drag projects in",
        body: "Drag any project pill onto the box pill to add it as a member; the count badge ticks up. The same drag that reorders pills assigns them — drop on the box instead of the strip. Shortcut: Alt-drag one pill onto another to box the two together in one move.",
      },
      {
        id: "box-dropdown",
        anchor: null,
        placement: "bottom",
        title: "Hover to see inside",
        body: "Hover the box pill to drop down its member list. Click a member to switch straight to it, or hit the × beside one to ungroup it (the project stays, it just leaves the box).",
      },
      {
        id: "box-scope",
        anchor: null,
        placement: "bottom",
        title: "Open, rename, delete",
        body: "Click the box pill itself to open the box scope, like opening a project. Right-click it for Open, Rename, or Delete — deleting a box never deletes its projects, only the grouping.",
      },
    ],
  },
  {
    id: "docker-sandbox",
    category: "Advanced",
    title: "Run a project in a container",
    blurb: "Confine a whole project's shells and agents to one closed Docker container — the folder stays on the host.",
    steps: [
      {
        id: "why-sandbox",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Box the whole project in",
        body: "By default a project's tabs run on your host with your full filesystem in reach. Turn on the container and every shell and agent tab of that project runs inside one closed, capability-dropped Docker container instead — so a misbehaving command or agent can't wander into unrelated host files. The project folder itself stays on the host, bind-mounted into the container at its exact same absolute path.",
      },
      {
        id: "open-pill-menu",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Right-click the project pill",
        body: "The toggle is per-project. Right-click the pill of the project you want to contain to open its context menu. (Offered for local projects only, and hidden on Windows.)",
      },
      {
        id: "flip-toggle",
        anchor: null,
        placement: "bottom",
        title: "\"Run this project in a container\"",
        body: "Click \"Run this project in a container\"; a ✓ appears once it's on, and clicking again turns it back off. Flipping it respawns every live tab into (or out of) the container — the pill warns first if that would drop a non-resumable agent conversation. Because the folder never moves, the file tree, git, viewers, and agent resume all keep working across the flip.",
      },
      {
        id: "image",
        anchor: null,
        placement: "bottom",
        title: "The image (auto-adopted or built)",
        body: "The first time you enable it, Eldrun adopts an in-repo Dockerfile or devcontainer image if there is one. If the image is missing, it opens a one-click build tab rather than failing silently. \"Container settings…\" in the same menu tunes the image, network, memory/CPU caps, and read-only rootfs — and those knobs survive turning the container off and on.",
      },
      {
        id: "lifetime",
        anchor: null,
        placement: "bottom",
        title: "One container, project-lived",
        body: "There's a single container per project (named eldrun-<id>), created when the project activates and removed when it deactivates — unless tabs are still live in it — then swept at startup. Shells and agents docker exec into it; only a local-agent tab deliberately stays on the host. Needs Docker installed.",
      },
    ],
  },
  {
    id: "add-ssh-project",
    category: "Advanced",
    title: "Add an SSH project",
    blurb: "Work on a folder living on another machine — Eldrun runs it over SSH/SFTP (no mount).",
    steps: [
      {
        id: "open-add-menu",
        anchor: '[data-hint-anchor="add-project"]',
        placement: "top",
        title: "Open the add menu",
        body: "Click the + button beside your project pills, then pick New Project or Import Project. Both dialogs can host the project on a remote machine.",
      },
      {
        id: "flip-ssh-toggle",
        anchor: null,
        placement: "bottom",
        title: "Flip the SSH toggle",
        body: "Tick \"Remote (SSH) project\" at the top of the dialog. The dialog switches to remote mode: pick a Local location — where the project's synced local working copy will live — and the SSH connection fields appear below.",
      },
      {
        id: "optional-vpn",
        anchor: null,
        placement: "bottom",
        title: "Behind a VPN? (optional)",
        body: "If the host is only reachable over a VPN, tick \"Connect via OpenVPN\", pick a .ovpn config (copied into Eldrun) and enter its passphrase, then hit Connect VPN before connecting SSH. Needs openvpn + polkit installed.",
      },
      {
        id: "connect-ssh",
        anchor: null,
        placement: "bottom",
        title: "Connect to the host",
        body: "Type the SSH address as user@host or host:2222. Leave the password blank to use your SSH key/agent, or fill it in for password auth. Click Connect — Eldrun verifies it can reach the host.",
      },
      {
        id: "browse-remote",
        anchor: null,
        placement: "bottom",
        title: "Pick the remote folder",
        body: "Once connected, a remote file browser appears. Step into the directory you want, then click \"Use this folder\". On New it creates a subfolder there; on Import it registers it in place.",
      },
      {
        id: "create-mount",
        anchor: null,
        placement: "bottom",
        title: "Create and connect",
        body: "Finish naming and pick a Git hosting option, then Create/Import. Eldrun pairs the remote folder with your synced local copy: agent tabs work locally in it by default, shells run on the host, and file browsing and git go over SSH/SFTP — no sshfs/FUSE. Later, the pill's connection lamp reconnects the project on demand.",
      },
    ],
  },
  {
    id: "ssh-via-openvpn",
    category: "Advanced",
    title: "SSH project via OpenVPN",
    blurb: "Reach a host that's only available behind a VPN, then mount its folder over SSH.",
    steps: [
      {
        id: "open-add-menu",
        anchor: '[data-hint-anchor="add-project"]',
        placement: "top",
        title: "Open the add menu",
        body: "Click the + button beside your project pills and pick New Project or Import Project. Either dialog can host the project on a VPN-gated remote.",
      },
      {
        id: "flip-ssh-toggle",
        anchor: null,
        placement: "bottom",
        title: "Flip the SSH toggle",
        body: "Tick \"Remote (SSH) project\" at the top. The dialog switches to remote mode: a Local location picker for the synced local working copy, then the SSH connection fields — with an OpenVPN tunnel section above them.",
      },
      {
        id: "enable-vpn",
        anchor: null,
        placement: "bottom",
        title: "Enable the VPN tunnel",
        body: "Tick \"Connect via OpenVPN\" when the host is only reachable through the tunnel — Eldrun brings the tunnel up first, then connects SSH through it. Needs openvpn + polkit (pkexec) installed locally.",
      },
      {
        id: "pick-ovpn",
        anchor: null,
        placement: "bottom",
        title: "Choose your .ovpn config",
        body: "Hit Browse… next to \"OpenVPN config\" and select your .ovpn file. Eldrun copies it into its own config store so the tunnel can be re-established later.",
      },
      {
        id: "connect-vpn",
        anchor: null,
        placement: "bottom",
        title: "Enter the credentials and connect",
        body: "Type the VPN passphrase — or the account username and password, if your .ovpn uses those — then click \"Connect VPN\". pkexec prompts for elevation, openvpn dials the tunnel, and the button flips to \"Connected\" once it's up.",
      },
      {
        id: "connect-ssh",
        anchor: null,
        placement: "bottom",
        title: "Now connect SSH",
        body: "With the tunnel up, type the SSH address as user@host or host:2222. Leave the password blank to use your SSH key/agent, or fill it in for password auth. Click Connect — Eldrun reaches the host through the VPN.",
      },
      {
        id: "browse-and-create",
        anchor: null,
        placement: "bottom",
        title: "Pick the folder and create",
        body: "Step through the remote browser to your directory and click \"Use this folder\". Finish naming, pick a Git hosting option, then Create/Import. Eldrun connects over SSH/SFTP and pairs the folder with a synced local working copy — no local mount.",
      },
    ],
  },
  {
    id: "vpn-tunnel",
    category: "Advanced",
    title: "Control the VPN tunnel",
    blurb: "Bring an OpenVPN tunnel up or down from the header — with or without a project behind it.",
    steps: [
      {
        id: "machine-wide",
        anchor: ".vpn-indicator-btn",
        placement: "bottom",
        title: "The OpenVPN indicator",
        body: "The header's OpenVPN button controls a machine-wide tunnel. It's not tied to any project: a config that pushes redirect-gateway reroutes your whole computer — browser included — for as long as it's up. So it lives here, always visible, not buried in one project.",
      },
      {
        id: "add-config",
        anchor: null,
        placement: "bottom",
        title: "Add a .ovpn config",
        body: "Open the menu and pick your .ovpn file — Eldrun copies it into its own config store so the tunnel can be re-established later. Every stored config is then listed here, ready to connect.",
      },
      {
        id: "up-down",
        anchor: null,
        placement: "bottom",
        title: "Connect or disconnect anytime",
        body: "Click a config to bring its tunnel up or down directly from the header — no project required. While one tunnel is up, project-scoped VPN sections collapse to a \"tunnel already up\" notice pointing back here, because a second tunnel would be a second claim on one machine's routing.",
      },
      {
        id: "auto-launch",
        anchor: null,
        placement: "bottom",
        title: "Connect on launch",
        body: "Toggle \"Connect on launch\" on a config to arm the tunnel at startup. It's exclusive — arming one disarms any other — and it never prompts: it's only offered when your saved credentials make the connect silent (tick \"Save passphrase\" when you first connect to enable it).",
      },
    ],
  },
  {
    id: "extend-to-remote",
    category: "Advanced",
    title: "Extend a local project to a remote",
    blurb: "Pair an existing local project with an SSH host — files stay local, git keeps the two in lockstep.",
    steps: [
      {
        id: "why-extend",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Take a local project remote",
        body: "Already have a local project and want a copy on another machine? Extending pairs it with an SSH host without moving your files: your local folder stays put and becomes the mirror, Eldrun creates a matching folder on the host, and git keeps the two in lockstep. It's the reverse of adding a fresh SSH project.",
      },
      {
        id: "right-click-pill",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Right-click the project pill",
        body: "Right-click the pill of the local project you want to extend to open its context menu, then pick \"Extend to remote…\". (It only shows for local projects — a project that's already remote has nothing to extend.)",
      },
      {
        id: "connect-host",
        anchor: null,
        placement: "bottom",
        title: "Connect to the host",
        body: "Type the SSH address as user@host or host:2222. Leave the password blank to use your SSH key/agent, or fill it in for password auth. If the host sits behind a VPN, flip \"Connect via OpenVPN\" (off by default) and bring up the tunnel first. Click Connect, then Next.",
      },
      {
        id: "pick-remote-folder",
        anchor: null,
        placement: "bottom",
        title: "Choose the remote folder",
        body: "A remote file browser appears. Step into the parent directory where the host copy should live and click \"Use this folder\" — Eldrun creates the project's folder there. Hit Next to review.",
      },
      {
        id: "review-and-extend",
        anchor: null,
        placement: "bottom",
        title: "Review Local ↔ Remote, then extend",
        body: "The summary shows your existing Local path paired with the new Remote path. Click \"Extend to remote\". Your local files aren't touched — they become the git-lockstep mirror, and you push them up to the host through git when you're ready.",
      },
    ],
  },
  {
    id: "compute-machines",
    category: "Advanced",
    title: "Add compute machines to a project",
    blurb: "Reach more than one host from a remote project — a shared cluster node or a synced experiment box.",
    steps: [
      {
        id: "why-machines",
        anchor: ".project-pills-region",
        placement: "top",
        title: "One project, many machines",
        body: "A remote project's primary host owns its files and git. But you can attach extra compute machines — a second GPU box, an HPC compute node — and run tabs on any of them. Each machine gets its own connection lamp and its own tab locality.",
      },
      {
        id: "open-hub",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Open \"Remote machines…\"",
        body: "Right-click the project pill → Runtime → \"Remote machines…\" (or click any of the pill's connection lamps). The hub lists the primary host first, then every worker machine, plus an \"Add a machine\" form.",
      },
      {
        id: "shared-vs-synced",
        anchor: null,
        placement: "bottom",
        title: "Shared folder, or a synced copy",
        body: "Add a machine and choose its kind. By default it shares the primary's project folder over a shared filesystem (an HPC node on a shared home) — Eldrun copies nothing and runs no git on it. Untick \"Sync a copy\" for that; leave it ticked to instead push a one-way, read-only copy of your code to a standalone box.",
      },
      {
        id: "sync-and-pull",
        anchor: null,
        placement: "bottom",
        title: "Sync code, pull outputs",
        body: "For a synced (copy) worker, \"Sync code now\" pushes your latest tracked files to it, and \"Pull outputs…\" brings its experiment results back — the one worker→local path, always size-confirmed. A shared-folder worker needs neither: its outputs already sit in the primary's folder.",
      },
      {
        id: "global-machines",
        anchor: ".machines-indicator-btn",
        placement: "bottom",
        title: "Or connect a global machine once",
        body: "The header's Machines indicator lets you authenticate a host once, project-independently, then drag it onto any project (its pill, or its open Remote machines window) to add it there as a shared-folder worker. Removing it from a project never disconnects it here.",
      },
      {
        id: "run-on-host",
        anchor: null,
        placement: "bottom",
        title: "Run a tab on a chosen machine",
        body: "Once a machine is attached, a tab can run on it — its shells and agents land on that host. That's how one project spans a login node for editing and a compute node for the heavy run.",
      },
    ],
  },
  {
    id: "persistent-sessions",
    category: "Advanced",
    title: "Keep long runs alive with sessions",
    blurb: "Shell tabs run inside tmux, so a run survives an SSH drop, a laptop sleep, or Eldrun quitting.",
    steps: [
      {
        id: "why-sessions",
        anchor: ".project-pills-region",
        placement: "top",
        title: "Runs that outlive the tab",
        body: "A shell or script tab runs inside a tmux session, decoupled from the connection. On a remote host that means a long run survives an SSH drop, a laptop sleep, a VPN drop, or Eldrun quitting; locally it even survives an Eldrun crash. It's ON by default — nothing to enable.",
      },
      {
        id: "which-tabs",
        anchor: null,
        placement: "bottom",
        title: "Which tabs are covered",
        body: "Shell tabs (a Python run opens one too) get a session. Agent tabs don't — they resume through their own mechanism — and the root scope never does. When you relaunch Eldrun, a covered tab reattaches to its still-running session instead of starting over.",
      },
      {
        id: "close-detaches",
        anchor: null,
        placement: "bottom",
        title: "Closing a tab detaches it",
        body: "Closing a tab is non-destructive: it kills only the SSH/PTY client, so the session lives on under its tmux daemon and stays reattachable. A quit, disconnect, crash, or respawn all leave the session running too — so a host can hold runs no tab currently points at.",
      },
      {
        id: "sessions-view",
        anchor: null,
        placement: "bottom",
        title: "The Sessions view (☰)",
        body: "Those orphaned runs are discoverable: the ☰ toggle in the file panel opens the Sessions view, which aggregates every live session across the primary and every connected worker, each row host-tagged. Click a row to attach a tab to it.",
      },
      {
        id: "kill-rename",
        anchor: null,
        placement: "bottom",
        title: "Kill or rename a session",
        body: "The only way to actually terminate a session is its × (kill) in the Sessions view — closing tabs never does. Each row also has Rename, which updates the owning tab's persisted name. To opt a whole project out, use the pill's \"Persistent sessions (tmux)\" toggle.",
      },
    ],
  },
  {
    id: "hpc-pipeline",
    category: "Advanced",
    title: "Run a job on an HPC cluster",
    blurb: "The guided SLURM pipeline: log in, create the project, upload data, submit a batch job, and watch it.",
    steps: [
      {
        id: "why-hpc",
        anchor: ".project-pills-region",
        placement: "top",
        title: "From login node to compute node",
        body: "An HPC cluster forbids real work on the login node — you describe a job in a batch script and the SLURM scheduler runs it on a compute node. The HPC pipeline is a 5-step wizard that walks the whole path: log in over SSH, create a remote project, upload inputs, submit the job, and watch it queue, run, and finish.",
      },
      {
        id: "open-add-menu",
        anchor: '[data-hint-anchor="add-project"]',
        placement: "bottom",
        title: "Open the + menu",
        body: "Click the + button beside your project pills, then pick \"HPC pipeline…\". The wizard opens on step 1 (Login) with the remote toggle already forced on — an HPC project is remote by definition.",
      },
      {
        id: "step-login",
        anchor: null,
        placement: "bottom",
        title: "1. Log in to the cluster",
        body: "Type the SSH address as user@host (add :port if it isn't 22). If the cluster is only reachable through your institution's VPN, tick \"Connect via OpenVPN\" and bring the tunnel up first. Connect, then browse to the parent folder on the host where the project should live — pick a place with quota/space, not a tiny $HOME — and click \"Use this folder\".",
      },
      {
        id: "step-project",
        anchor: null,
        placement: "bottom",
        title: "2. Create the project",
        body: "Give it a name and pick a Local location for its synced mirror — Eldrun keeps a local git-lockstep copy of the tracked files there while the real tree lives on the host. Click \"Create project\". Because it's git-backed, lockstep turns on automatically: a saved edit to a tracked file only reaches the host once you commit it.",
      },
      {
        id: "step-data",
        anchor: null,
        placement: "bottom",
        title: "3. Load data (optional)",
        body: "\"Add files…\" streams a few local input files straight to the project on the host over SFTP. For large trees, skip this and mark the folder auto-sync in the file panel later instead. Hit Next (or Skip).",
      },
      {
        id: "step-run-account",
        anchor: null,
        placement: "bottom",
        title: "4. Set your account and resources",
        body: "A starter job.slurm is prepared; edit its #SBATCH directives in the grid. Set Account to your working group's allocation — most clusters reject a job with no account — and set a real Partition (the <partition> placeholder is only a hint). Adjust Time, Nodes, Tasks, CPUs, Memory and GPUs to your job.",
      },
      {
        id: "step-run-submit",
        anchor: null,
        placement: "bottom",
        title: "4. Submit the job",
        body: "Also fix the script body: the starter's `module load Python` is a placeholder — use your cluster's real module name (run `module avail` to find it). Click \"⏫ Submit job\". Eldrun writes the script to the host and runs sbatch on a compute node, then opens a log tab that tails the output.",
      },
      {
        id: "step-watch",
        anchor: null,
        placement: "bottom",
        title: "5. Watch it run",
        body: "The log tab is already following the job's output (it waits out the queue). Open the Jobs view — the ⚙ toggle in the file panel — to see the job queue, run, and finish, with per-job Watch and Cancel. That's the whole pipeline; you can re-run it any time from the + menu.",
      },
      {
        id: "without-wizard",
        anchor: null,
        placement: "bottom",
        title: "Beyond the wizard",
        body: "On any remote project that has sbatch, opening a file with a #SBATCH line shows a SLURM bar in the viewer: Submit job, a Variables form for the directives (including Account), and \"⚡ Interactive session…\" to land an srun --pty shell on a compute node. The Jobs view (⚙ in the file panel) tracks everything you've launched.",
      },
    ],
  },
];
