import { useCallback, useEffect, useMemo, useState } from "react";
import { api, type CalendarAction, type MobileCalendar, type MobileCalendarEvent, type MobileCalendarEventInput, type MobileCalendarInfo } from "../api";

const NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const today = () => { const n = new Date(); return `${n.getFullYear()}-${String(n.getMonth() + 1).padStart(2, "0")}-${String(n.getDate()).padStart(2, "0")}`; };
const monthOf = (date = today()) => date.slice(0, 7);
const dayId = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
const addDays = (date: string, amount: number) => { const [y, m, d] = date.split("-").map(Number); return dayId(new Date(y, m - 1, d + amount, 12)); };
const addMonths = (month: string, amount: number) => { const [y, m] = month.split("-").map(Number); const d = new Date(y, m - 1 + amount, 1); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`; };
const grid = (month: string, weekStart: 0 | 1) => { const [y, m] = month.split("-").map(Number); const first = new Date(y, m - 1, 1, 12); const start = addDays(`${month}-01`, -((first.getDay() - weekStart + 7) % 7)); return Array.from({ length: 42 }, (_, i) => addDays(start, i)); };
const datePart = (stamp: string) => stamp.slice(0, 10);
const eventEnd = (event: MobileCalendarEvent) => event.all_day || event.end.endsWith("T00:00") ? datePart(event.end) : addDays(datePart(event.end), 1);
const happensOn = (event: MobileCalendarEvent, date: string) => date >= datePart(event.start) && date < eventEnd(event);
const dateTitle = (date: string) => new Intl.DateTimeFormat(undefined, { weekday: "long", month: "long", day: "numeric", year: "numeric" }).format(new Date(`${date}T12:00`));

const blankEvent = (date: string, calendars: MobileCalendarInfo[]): MobileCalendarEventInput => ({ calendar_id: calendars.find((c) => !c.readonly)?.id ?? "", start: `${date}T09:00`, end: `${date}T10:00`, all_day: false, title: "", location: "", notes: "", conference: "", category: "", status: "confirmed" });
const inputOf = (event: MobileCalendarEvent, calendarId: string): MobileCalendarEventInput => ({ calendar_id: calendarId, start: event.start, end: event.end, all_day: event.all_day, title: event.title, location: event.location ?? "", notes: event.notes ?? "", conference: event.conference ?? "", category: event.category ?? "", status: event.status ?? "confirmed" });

/** The desktop stores an all-day end as the day *after* the last day (iCal's
 * exclusive DTEND), while "Ends" in an editor means the last day itself. These
 * convert between the two, exactly as the desktop dialog does — without them a
 * single-day all-day event was sent with `end == start` and rejected, and a
 * reopened one showed the day after it actually ends. */
export const shownAllDayEnd = (start: string, end: string) => { const last = addDays(datePart(end), -1); return last >= datePart(start) ? last : datePart(start); };
export const storedAllDayEnd = (day: string) => addDays(day, 1);
type Editing = { event?: MobileCalendarEvent; draft: MobileCalendarEventInput } | null;

export function Calendar({ back }: { back: () => void }) {
  const [month, setMonth] = useState(monthOf); const [selected, setSelected] = useState(today);
  const [data, setData] = useState<MobileCalendar | null>(null); const [editing, setEditing] = useState<Editing>(null);
  const [manage, setManage] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setBusy(true); setError(""); try { const { calendar } = await api<{ calendar: MobileCalendar }>(`/api/v1/calendar?month=${month}`); setData(calendar); setSelected((d) => d.startsWith(month) ? d : `${month}-01`); } catch (e) { setError(`Desktop calendar unavailable: ${String(e)}`); } finally { setBusy(false); } }, [month]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (action: CalendarAction) => { setBusy(true); setError(""); try { const { calendar } = await api<{ calendar: MobileCalendar }>(`/api/v1/calendar?month=${month}`, { method: "POST", body: JSON.stringify(action) }); setData(calendar); return true; } catch (e) { setError(String(e)); return false; } finally { setBusy(false); } };
  const weekStart = data?.week_start ?? 0; const days = useMemo(() => grid(month, weekStart), [month, weekStart]);
  const events = useCallback((date: string) => (data?.events ?? []).filter((event) => happensOn(event, date)), [data]);
  const selectedEvents = useMemo(() => events(selected).sort((a, b) => Number(b.all_day) - Number(a.all_day) || a.start.localeCompare(b.start)), [events, selected]);
  const label = useMemo(() => new Intl.DateTimeFormat(undefined, { month: "long", year: "numeric" }).format(new Date(`${month}-01T12:00`)), [month]);
  const open = (event: MobileCalendarEvent) => { if (event.calendar_id) setEditing({ event, draft: inputOf(event, event.calendar_id) }); };
  return <main className="screen mobile-calendar-screen">
    <header><button className="back" onClick={back}>‹</button><h1>Calendar</h1><button onClick={() => void load()} disabled={busy}>↻</button></header>
    <div className="mobile-calendar-actions"><button className="primary" disabled={busy || !data?.calendars.some((c) => !c.readonly)} onClick={() => setEditing({ draft: blankEvent(selected, data?.calendars ?? []) })}>+ Event</button><button disabled={busy} onClick={() => setManage(true)}>Calendars</button></div>
    {error && <p className="error">{error}</p>}
    <div className="mobile-calendar-nav"><button onClick={() => setMonth((m) => addMonths(m, -1))} disabled={busy}>‹</button><strong>{label}</strong><button onClick={() => setMonth((m) => addMonths(m, 1))} disabled={busy}>›</button></div>
    <section className="mobile-calendar-grid" aria-label={label}>{Array.from({ length: 7 }, (_, i) => <span className="mobile-calendar-weekday" key={NAMES[(i + weekStart) % 7]}>{NAMES[(i + weekStart) % 7]}</span>)}{days.map((date) => { const rows = events(date); return <button className={`mobile-calendar-day${date.startsWith(month) ? "" : " outside"}${date === selected ? " selected" : ""}${date === today() ? " today" : ""}`} key={date} onClick={() => setSelected(date)}><span>{Number(date.slice(-2))}</span><i className="mobile-calendar-dots">{rows.slice(0, 3).map((event, i) => <b key={`${event.id}-${i}`} style={{ backgroundColor: event.color }} />)}</i></button>; })}</section>
    {data?.truncated && <p className="mobile-calendar-warning">This busy month is shortened for the mobile view.</p>}
    <section className="mobile-calendar-agenda"><h2>{dateTitle(selected)}</h2>{selectedEvents.length ? selectedEvents.map((event) => <button className={`mobile-calendar-event${event.status === "cancelled" ? " cancelled" : ""}`} key={`${event.id}-${event.occurrence_start}`} onClick={() => open(event)}><i style={{ backgroundColor: event.color }} /><div><small>{event.all_day ? "All day" : event.start.slice(11, 16)}{event.recurring ? " · Repeats" : ""}</small><strong>{event.title || "Untitled event"}</strong>{event.location && <span>{event.location}</span>}</div></button>) : <p>No events scheduled.</p>}</section>
    {editing && <EventEditor editing={editing} calendars={data?.calendars ?? []} busy={busy} close={() => setEditing(null)} save={async (event) => { const eventId = editing.event?.id; const ok = await mutate(eventId ? { type: "update_event", event_id: eventId, event } : { type: "create_event", event }); if (ok) setEditing(null); }} remove={editing.event ? async () => { const eventId = editing.event?.id; if (eventId && window.confirm(`Delete “${editing.event?.title}”?`) && await mutate({ type: "delete_event", event_id: eventId })) setEditing(null); } : undefined} />}
    {manage && <CalendarManager calendars={data?.calendars ?? []} busy={busy} mutate={mutate} close={() => setManage(false)} />}
  </main>;
}

function EventEditor({ editing, calendars, busy, close, save, remove }: { editing: Exclude<Editing, null>; calendars: MobileCalendarInfo[]; busy: boolean; close: () => void; save: (value: MobileCalendarEventInput) => Promise<void>; remove?: () => Promise<void> }) {
  const [draft, setDraft] = useState(editing.draft); const patch = (change: Partial<MobileCalendarEventInput>) => setDraft((v) => ({ ...v, ...change }));
  const startDay = datePart(draft.start), startTime = draft.start.slice(11, 16) || "09:00", endTime = draft.end.slice(11, 16) || "10:00";
  const endDay = draft.all_day ? shownAllDayEnd(draft.start, draft.end) : datePart(draft.end);
  const setTime = (which: "start" | "end", day: string, time: string) => {
    if (!draft.all_day) { patch({ [which]: `${day}T${time}` } as Partial<MobileCalendarEventInput>); return; }
    if (which === "end") { patch({ end: storedAllDayEnd(day) }); return; }
    // Moving an all-day start past the end would otherwise be refused on save.
    patch({ start: day, end: storedAllDayEnd(day) > draft.end ? storedAllDayEnd(day) : draft.end });
  };
  return <div className="todo-editor-backdrop"><form className="todo-editor todo-editor-full calendar-editor" onSubmit={(e) => { e.preventDefault(); if (draft.title.trim()) void save(draft); }}><div className="todo-editor-heading"><h2>{editing.event ? "Edit event" : "New event"}</h2><button type="button" onClick={close}>×</button></div><label>Title<input autoFocus required maxLength={300} value={draft.title} onChange={(e) => patch({ title: e.target.value })} /></label><label>Calendar<select value={draft.calendar_id} onChange={(e) => patch({ calendar_id: e.target.value })}>{calendars.map((c) => <option key={c.id} value={c.id} disabled={c.readonly}>{c.name}{c.readonly ? " (read-only)" : ""}</option>)}</select></label><label className="todo-inline-check"><input type="checkbox" checked={draft.all_day} onChange={(e) => patch(e.target.checked ? { all_day: true, start: startDay, end: storedAllDayEnd(endDay >= startDay ? endDay : startDay) } : { all_day: false, start: `${startDay}T${startTime}`, end: `${endDay}T${endTime}` })} /> All day</label><div className="todo-editor-grid"><label>Starts<input type="date" value={startDay} onChange={(e) => setTime("start", e.target.value, startTime)} />{!draft.all_day && <input type="time" value={startTime} onChange={(e) => setTime("start", startDay, e.target.value)} />}</label><label>Ends<input type="date" value={endDay} onChange={(e) => setTime("end", e.target.value, endTime)} />{!draft.all_day && <input type="time" value={endTime} onChange={(e) => setTime("end", endDay, e.target.value)} />}</label></div><label>Location<input value={draft.location} maxLength={1000} onChange={(e) => patch({ location: e.target.value })} /></label><label>Conference link<input type="url" value={draft.conference} maxLength={2000} onChange={(e) => patch({ conference: e.target.value })} /></label><label>Notes<textarea rows={4} value={draft.notes} maxLength={16 * 1024} onChange={(e) => patch({ notes: e.target.value })} /></label><div className="todo-editor-grid"><label>Category<input value={draft.category} maxLength={80} onChange={(e) => patch({ category: e.target.value })} /></label><label>Status<select value={draft.status} onChange={(e) => patch({ status: e.target.value })}><option value="confirmed">Confirmed</option><option value="tentative">Tentative</option><option value="cancelled">Cancelled</option></select></label></div>{editing.event?.recurring && <p className="notice">This edits the entire recurring series; individual occurrences remain managed on desktop.</p>}<div className="todo-editor-actions">{remove && <button type="button" className="danger" onClick={() => void remove()} disabled={busy}>Delete</button>}<span /><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={busy || !draft.title.trim() || !draft.calendar_id}>Save</button></div></form></div>;
}

function CalendarManager({ calendars, busy, mutate, close }: { calendars: MobileCalendarInfo[]; busy: boolean; mutate: (action: CalendarAction) => Promise<boolean>; close: () => void }) {
  const [name, setName] = useState(""); const [color, setColor] = useState("#4aa3df");
  return <div className="todo-editor-backdrop"><section className="todo-editor todo-editor-full calendar-manager"><div className="todo-editor-heading"><h2>Calendars</h2><button onClick={close}>×</button></div>{calendars.map((c) => <article className="mobile-calendar-manage-row" key={c.id}><i style={{ backgroundColor: c.color }} /><div><strong>{c.name}</strong><small>{c.readonly ? "Read-only" : c.caldav ? "CalDAV" : c.source_url ? "Subscribed" : "Local"}</small></div><label className="todo-inline-check"><input type="checkbox" checked={c.visible} disabled={busy} onChange={() => void mutate({ type: "update_calendar", calendar_id: c.id, name: c.name, color: c.color, visible: !c.visible })} /> Show</label>{!c.readonly && <><button disabled={busy} onClick={() => { const nextName = window.prompt("Calendar name", c.name); if (!nextName?.trim()) return; const nextColor = window.prompt("Calendar color (#rrggbb)", c.color); if (nextColor?.trim()) void mutate({ type: "update_calendar", calendar_id: c.id, name: nextName.trim(), color: nextColor.trim(), visible: c.visible }); }}>Edit</button><button className="danger" disabled={busy || calendars.length <= 1} onClick={() => { if (window.confirm(`Delete “${c.name}” and its events?`)) void mutate({ type: "delete_calendar", calendar_id: c.id }); }}>Delete</button></>}</article>)}<form className="calendar-new" onSubmit={(e) => { e.preventDefault(); if (name.trim()) void mutate({ type: "create_calendar", name: name.trim(), color }).then((ok) => { if (ok) setName(""); }); }}><label>Name<input value={name} maxLength={160} onChange={(e) => setName(e.target.value)} /></label><label>Color<input type="color" value={color} onChange={(e) => setColor(e.target.value)} /></label><button className="primary" disabled={busy || !name.trim()}>Add calendar</button></form></section></div>;
}
